version: 2.1
orbs:
  architect: giantswarm/architect@4.28.1

workflows:
  package-and-push-chart-on-tag:
    jobs:
    - architect/go-build:
        context: architect
        name: go-build
        binary: azure-private-endpoint-operator
        resource_class: xlarge
        filters:
          tags:
            only: /^v.*/

    - architect/push-to-docker:
        context: "architect"
        name: push-azure-private-endpoint-operator-to-quay
        image: "quay.io/giantswarm/azure-private-endpoint-operator"
        username_envar: "QUAY_USERNAME"
        password_envar: "QUAY_PASSWORD"
        requires:
        - go-build
        filters:
          # Trigger the job also on git tag.
          tags:
            only: /^v.*/

    - architect/push-to-app-catalog:
        context: "architect"
        name: push-to-app-catalog
        app_catalog: "control-plane-catalog"
        app_catalog_test: "control-plane-test-catalog"
        chart: "azure-private-endpoint-operator"
        requires:
        - push-azure-private-endpoint-operator-to-quay
        # Trigger job on git tag.
        filters:
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        context: architect
        name: push-to-capz-app-collection
        app_name: "azure-private-endpoint-operator"
        app_collection_repo: "capz-app-collection"
        requires:
        - push-azure-private-endpoint-operator-to-quay
        - push-to-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
