version: 2.1
orbs:
  architect: giantswarm/architect@4.35.5

jobs:
  unit-tests:
    executor: architect/architect
    steps:
      - checkout
      - run:
          name: "Run unit tests"
          command: CGO_ENABLED=0 make test-unit

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/go-build:
          context: architect
          name: go-build
          binary: azure-private-endpoint-operator
          resource_class: xlarge
          filters:
            tags:
              only: /^v.*/

      - unit-tests:
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - unit-tests
          filters:
          # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          name: push-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "azure-private-endpoint-operator"
          requires:
            - push-to-registries
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-capz-app-collection
          app_name: "azure-private-endpoint-operator"
          app_collection_repo: "capz-app-collection"
          requires:
            - push-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
