# permissions for end users to view azureclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: azurecluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: azure-private-endpoint-operator
    app.kubernetes.io/part-of: azure-private-endpoint-operator
    app.kubernetes.io/managed-by: kustomize
  name: azurecluster-viewer-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io.giantswarm.io
  resources:
  - azureclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io.giantswarm.io
  resources:
  - azureclusters/status
  verbs:
  - get
