apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: {{ include "resource.default.name"  . }}-exceptions
  namespace: {{ include "resource.default.namespace"  . }}
spec:
  exceptions:
  - policyName: disallow-host-ports
    ruleNames:
    - host-ports-none
    - autogen-host-ports-none
  - policyName: disallow-host-namespaces
    ruleNames:
    - host-namespaces
    - autogen-host-namespaces

  match:
    any:
    - resources:
        kinds:
        - Deployment
        - ReplicaSet
        - Pod
        namespaces:
        - {{ include "resource.default.namespace"  . }}
        names:
        - {{ include "resource.default.name"  . }}*
